### ISSUE TITLE
data dir Issues

### ISSUE THREAD

**Issue by prj-jxust** [Megvii-BaseDetection/BorderDet#1]
pods_train --num-gpus 1
soft link to /data/Outputs/model_logs/cvpods_playground/detection/coco/borderdet/borderdet.res50.fpn.coco.800size.1x
ln: 无法创建符号链接'log': 文件已存在
Command Line Args: Namespace(dist_url='tcp://127.0.0.1:50152', eval_only=False, machine_rank=0, num_gpus=1, num_machines=1, opts=[], resume=False)
Traceback (most recent call last):
  File "/home/p/BorderDet-master/tools/train_net.py", line 222, in <module>
    args=(args,),
  File "/home/p/BorderDet-master/cvpods/engine/launch.py", line 55, in launch
    main_func(*args)
  File "/home/p/BorderDet-master/tools/train_net.py", line 203, in main
    stage_main(args, config, build_model)
  File "/home/p/BorderDet-master/tools/train_net.py", line 126, in stage_main
    cfg, logger = default_setup(cfg, args)
  File "/home/p/BorderDet-master/cvpods/engine/setup.py", line 76, in default_setup
    PathManager.mkdirs(output_dir)
  File "/home/p/BorderDet-master/cvpods/utils/file/file_io.py", line 446, in mkdirs
    return PathManager.__get_path_handler(path)._mkdirs(path)
  File "/home/p/BorderDet-master/cvpods/utils/file/file_io.py", line 252, in _mkdirs
    os.makedirs(path, exist_ok=True)
  File "/home/p/anaconda3/envs/pytorch/lib/python3.7/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/home/p/anaconda3/envs/pytorch/lib/python3.7/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/home/p/anaconda3/envs/pytorch/lib/python3.7/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  [Previous line repeated 4 more times]
  File "/home/p/anaconda3/envs/pytorch/lib/python3.7/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/data'

**Comment by prj-jxust** [comment]
cd your file/BorderDet-master/playground/detection/coco/borderdet/borderdet.res50.fpn.coco.800size.1x/datasets
delete coco
next  
ln -s /path/to/your /coco

**Comment by poodarchu** [comment]
you can change the output dir in the config.py from '/data/xxxx' to your desired dump directories.

**Comment by prj-jxust** [comment]
The problem has been solved，thanks！
