### ISSUE TITLE
undefined symbol: 

### ISSUE THREAD

**Issue by chenzhe222** [Megvii-BaseDetection/BorderDet#28]
Traceback (most recent call last):
  File "/home/chen/code/BorderDet/tools/train_net.py", line 26, in <module>
    from cvpods.checkpoint import DetectionCheckpointer
  File "/home/chen/code/BorderDet/cvpods/__init__.py", line 3, in <module>
    from .utils import setup_environment
  File "/home/chen/code/BorderDet/cvpods/utils/__init__.py", line 11, in <module>
    from .visualizer import colormap, random_color, VideoVisualizer, ColorMode, VisImage, Visualizer
  File "/home/chen/code/BorderDet/cvpods/utils/visualizer/__init__.py", line 5, in <module>
    from .video_visualizer import *
  File "/home/chen/code/BorderDet/cvpods/utils/visualizer/video_visualizer.py", line 6, in <module>
    from .visualizer import ColorMode, Visualizer, _create_text_labels, _PanopticPrediction
  File "/home/chen/code/BorderDet/cvpods/utils/visualizer/visualizer.py", line 15, in <module>
    from cvpods.structures import BitMasks, Boxes, BoxMode, Keypoints, PolygonMasks, RotatedBoxes
  File "/home/chen/code/BorderDet/cvpods/structures/__init__.py", line 2, in <module>
    from .boxes import Boxes, BoxMode, pairwise_iou, pairwise_ioa
  File "/home/chen/code/BorderDet/cvpods/structures/boxes.py", line 8, in <module>
    from cvpods.layers import cat
  File "/home/chen/code/BorderDet/cvpods/layers/__init__.py", line 3, in <module>
    from .deform_conv import DeformConv, ModulatedDeformConv
  File "/home/chen/code/BorderDet/cvpods/layers/deform_conv.py", line 10, in <module>
    from cvpods import _C
ImportError: /home/chen/code/BorderDet/cvpods/_C.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN6cvpods25border_align_cuda_forwardERKN2at6TensorES3_S3_i

**Comment by FateScript** [comment]
The version of NVCC you use to build cvpods or torchvision does not match the version of CUDA you are running with. This often happens when using anaconda's CUDA runtime.

Uninstalling torch and torchvision and deleting the copies from /lib/python3.6/site-packages/ and reinstalling them might fix your issue.
