### ISSUE TITLE
AssertionError: Default process group is not initialized

### ISSUE THREAD

**Issue by SnowsmileCarina** [Megvii-BaseDetection/BorderDet#4]
I only have a single GPU, so  i use 'pods_train --num-gpus 1' to train the model. Here is the Error i'm getting:

ERROR [08/06 03:03:31 pods.engine.trainer]: Exception during training:
Traceback (most recent call last):
  File "/home/BorderDet/cvpods/engine/trainer.py", line 90, in train
    self.run_step()
  File "/home/BorderDet/cvpods/engine/trainer.py", line 194, in run_step
    loss_dict = self.model(data)
  File "/home/sdb/anaconda2/envs/mmdet/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/BorderDet/cvpods/modeling/meta_arch/borderdet.py", line 167, in forward
    bd_box_delta,
  File "/home/BorderDet/cvpods/modeling/meta_arch/borderdet.py", line 234, in losses
    dist.all_reduce(num_foreground)
  File "/home/sdb/anaconda2/envs/mmdet/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 897, in all_reduce
    _check_default_pg()
  File "/home/sdb/anaconda2/envs/mmdet/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 187, in _check_default_pg
    "Default process group is not initialized"
AssertionError: Default process group is not initialized
[08/06 03:03:31 pods.engine.hooks]: Total training time: 0:00:00 (0:00:00 on hooks)

**Comment by SnowsmileCarina** [comment]
The issue is solved. If you have only a single GPU, you need to comment out all the codes containing 'dist' in cvpods/modeling/meta_arch/borderdet.py
