### ISSUE TITLE
code issue

### ISSUE THREAD

**Issue by xiexu0210** [Megvii-BaseDetection/BorderDet#50]
hi,
I have a problem in your code.
Could you give me some advise.
-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/home/chrisd/.pyenv/versions/anaconda3-4.3.1/envs/FCOS/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/home/chrisd/桌面/代码/cvpods/cvpods/engine/launch.py", line 88, in _distributed_worker
    main_func(*args)
  File "/home/chrisd/桌面/代码/cvpods/tools/train_net.py", line 95, in main
    runner.train()
  File "/home/chrisd/桌面/代码/cvpods/cvpods/engine/runner.py", line 270, in train
    super().train(self.start_iter, self.start_epoch, self.max_iter)
  File "/home/chrisd/桌面/代码/cvpods/cvpods/engine/base_runner.py", line 84, in train
    self.run_step()
  File "/home/chrisd/桌面/代码/cvpods/cvpods/engine/base_runner.py", line 185, in run_step
    loss_dict = self.model(data)
  File "/home/chrisd/.pyenv/versions/anaconda3-4.3.1/envs/FCOS/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/chrisd/.pyenv/versions/anaconda3-4.3.1/envs/FCOS/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 447, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/home/chrisd/.pyenv/versions/anaconda3-4.3.1/envs/FCOS/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/chrisd/桌面/代码/BorderDet/playground/detection/coco/borderdet/borderdet.res50.fpn.coco.800size.1x/borderdet.py", line 147, in forward
    ) = self.head(features, shifts)
  File "/home/chrisd/.pyenv/versions/anaconda3-4.3.1/envs/FCOS/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/chrisd/桌面/代码/BorderDet/playground/detection/coco/borderdet/borderdet.res50.fpn.coco.800size.1x/borderdet.py", line 734, in forward
    border_cls_conv = self.border_cls_subnet(cls_subnet, align_boxes, wh)
  File "/home/chrisd/.pyenv/versions/anaconda3-4.3.1/envs/FCOS/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/chrisd/桌面/代码/BorderDet/playground/detection/coco/borderdet/borderdet.res50.fpn.coco.800size.1x/borderdet.py", line 809, in forward
    ltrb_conv = self.border_align(feature, boxes)
  File "/home/chrisd/.pyenv/versions/anaconda3-4.3.1/envs/FCOS/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/chrisd/桌面/代码/cvpods/cvpods/layers/border_align.py", line 42, in forward
    output = border_align(feature, boxes, wh, self.pool_size)
  File "/home/chrisd/桌面/代码/cvpods/cvpods/layers/border_align.py", line 15, in forward
    output = _C.border_align_forward(input, boxes, wh, pool_size)
RuntimeError: cuda runtime error (98) : invalid device function at /home/chrisd/桌面/代码/cvpods/cvpods/layers/csrc/border_align/border_align_kernel.cu:202

**Comment by ElectronicElephant** [comment]
I think there is a nvcc / cuda version miss match.
